### ISSUE TITLE
Back-End: Setup Django and React Project Skeleton

### ISSUE THREAD

**Issue by franklee77** [technocore-redux/youcanhireus#8]
The project's skeleton should be:
- Django 1.10+ to serve up the website and to operate the API layer
- React with Webpack 
- SQLite or Postgres? 

Django is designed to work with either SQLite or Postgres, so we can pretty easily switch between them. The model layer of Django deals with interactions with the database for us.

**Comment by franklee77** [comment]
We can use this as the starting point for setting up the project structure: http://geezhawk.github.io/using-react-with-django-rest-framework

**Comment by clayhan** [comment]
I think Postgres? Haven't seen many people use SQLite. Open to either!

**Comment by franklee77** [comment]
Since SQLite comes built-in with Django, lets use it for now and switch to Postgres once we get closer to production. 

Accidentally pushed the skeleton to master. My bad :(
